name: 📚 Documentation Issue
description: Report an issue with documentation
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation!

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      options:
        - README
        - API Reference
        - Examples
        - Error Handling Guide
        - SQLite Persistence Guide
        - Metrics & Telemetry Guide
        - Contributing Guide
        - TypeScript Definitions
        - Other
    validations:
      required: true

  - type: textarea
    id: issue
    attributes:
      label: Issue Description
      description: What's wrong with the documentation?
      placeholder: |
        - The example doesn't work
        - Information is outdated
        - Missing important details
        - Confusing explanation
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Location
      description: Where is the issue? (file path, section, line number)
      placeholder: |
        File: docs/API_REFERENCE.md
        Section: "Vector Stores"
        Line: 145
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Fix
      description: How should the documentation be improved?
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other relevant information
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I'm willing to submit a PR to fix this
          required: false
